# Generated by Django 5.2.7 on 2025-11-03 12:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel_Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hscode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master_hscode')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master_vessels')),
            ],
            options={
                'db_table': 'vessel_data',
            },
        ),
    ]
