# Generated by Django 5.2.7 on 2025-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel_data',
            name='hire_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vessel_data',
            name='market_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
