# Generated by Django 5.2.7 on 2025-11-03 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_data', '0002_vessel_data_hire_rate_vessel_data_market_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel_data',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
