# Generated by Django 5.2.7 on 2025-11-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_vessels_vessel_code'),
        ('vessel_data', '0003_vessel_data_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel_data',
            old_name='date',
            new_name='market_date',
        ),
        migrations.AlterField(
            model_name='vessel_data',
            name='hscode',
            field=models.ForeignKey(db_column='hscode', on_delete=django.db.models.deletion.CASCADE, to='masters.master_hscode'),
        ),
        migrations.AlterModelTable(
            name='vessel_data',
            table='market_rate',
        ),
    ]
