# Generated by Django 5.2.8 on 2025-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_data', '0004_rename_date_vessel_data_market_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel_data',
            name='market_date',
            field=models.DateTimeField(),
        ),
    ]
