# Generated by Django 5.2.8 on 2025-11-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_data', '0005_alter_vessel_data_market_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel_data',
            name='market_date',
            field=models.DateField(),
        ),
    ]
