# Generated by Django 5.2.7 on 2025-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_role',
            name='form_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_role',
            name='process_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
