# Generated by Django 5.2.7 on 2025-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_vessels',
            name='vessel_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
