# Generated by Django 5.2.7 on 2025-11-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_vessels_vessel_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_hscode',
            old_name='hscode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='master_hscode',
            old_name='hscode_name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='master_vessels',
            name='dead_weight',
            field=models.IntegerField(default=32),
        ),
    ]
