# Generated by Django 5.2.7 on 2025-11-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='process',
        ),
    ]
