# Generated by Django 5.2.7 on 2025-11-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_forms_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='form_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='process',
            name='process_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
