# Generated by Django 5.2.7 on 2025-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_forms_form_code_process_process_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='form_code',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_code',
        ),
        migrations.RemoveField(
            model_name='profile_mapping',
            name='form',
        ),
        migrations.RemoveField(
            model_name='profile_mapping',
            name='process',
        ),
        migrations.AddField(
            model_name='profile_mapping',
            name='form_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile_mapping',
            name='process_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forms',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
