# Generated by Django 5.2.7 on 2025-11-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_forms_form_code_remove_process_process_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='profile_mapping',
        ),
    ]
